/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitudes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_solicitudes_get"];
        put?: never;
        /** Create */
        post: operations["create_solicitudes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitudes/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request */
        get: operations["get_request_solicitudes__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct */
        patch: operations["correct_solicitudes__request_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Area
         * @enum {string}
         */
        Area: "backend" | "frontend" | "data" | "devops" | "producto" | "digital_transformation";
        /**
         * Categoria
         * @enum {string}
         */
        Categoria: "bug" | "datos" | "acceso" | "automatizacion" | "consulta" | "otro";
        /** CorrectionOut */
        CorrectionOut: {
            /** Previous Values */
            previous_values: {
                [key: string]: unknown;
            };
            /** New Values */
            new_values: {
                [key: string]: unknown;
            };
            /** Author */
            author: string;
            /** Reason */
            reason: string | null;
            /** Created At */
            created_at: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Error */
            error: string;
            /** Detail */
            detail: string;
            /** Fields */
            fields?: components["schemas"]["FieldError"][] | null;
            /** Kind */
            kind?: string | null;
        };
        /** FieldError */
        FieldError: {
            /** Loc */
            loc: string[];
            /** Msg */
            msg: string;
        };
        /**
         * Idioma
         * @enum {string}
         */
        Idioma: "es" | "pt";
        /** Item */
        Item: {
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Source Area */
            source_area: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "classified" | "failed";
            categoria: components["schemas"]["Categoria"] | null;
            prioridad: components["schemas"]["Prioridad"] | null;
            area_sugerida: components["schemas"]["Area"] | null;
            idioma: components["schemas"]["Idioma"] | null;
            /** Resumen */
            resumen: string | null;
            /** Requiere Info */
            requiere_info: boolean | null;
            /** Pregunta Seguimiento */
            pregunta_seguimiento: string | null;
            /** Confianza */
            confianza: number | null;
            /** Version Prompt */
            version_prompt: string | null;
            /** Provider */
            provider: string | null;
            /** Model */
            model: string | null;
            /** Needs Review */
            needs_review: boolean;
            /** Corrected */
            corrected: boolean;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ItemDetail */
        ItemDetail: {
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Source Area */
            source_area: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "classified" | "failed";
            categoria: components["schemas"]["Categoria"] | null;
            prioridad: components["schemas"]["Prioridad"] | null;
            area_sugerida: components["schemas"]["Area"] | null;
            idioma: components["schemas"]["Idioma"] | null;
            /** Resumen */
            resumen: string | null;
            /** Requiere Info */
            requiere_info: boolean | null;
            /** Pregunta Seguimiento */
            pregunta_seguimiento: string | null;
            /** Confianza */
            confianza: number | null;
            /** Version Prompt */
            version_prompt: string | null;
            /** Provider */
            provider: string | null;
            /** Model */
            model: string | null;
            /** Needs Review */
            needs_review: boolean;
            /** Corrected */
            corrected: boolean;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Original Classification */
            original_classification: {
                [key: string]: unknown;
            } | null;
            /** Corrections */
            corrections: components["schemas"]["CorrectionOut"][];
        };
        /** Page */
        Page: {
            /** Items */
            items: components["schemas"]["Item"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PatchBody */
        PatchBody: {
            categoria?: components["schemas"]["Categoria"];
            prioridad?: components["schemas"]["Prioridad"];
            area_sugerida?: components["schemas"]["Area"];
            idioma?: components["schemas"]["Idioma"];
            /** Resumen */
            resumen?: string;
            /** Requiere Info */
            requiere_info?: boolean;
            /** Pregunta Seguimiento */
            pregunta_seguimiento?: string | null;
            /** Author */
            author: string;
            /** Reason */
            reason?: string | null;
        };
        /**
         * Prioridad
         * @enum {string}
         */
        Prioridad: "alta" | "media" | "baja";
        /** RequestInput */
        RequestInput: {
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Source Area */
            source_area?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_requests_solicitudes_get: {
        parameters: {
            query?: {
                categoria?: components["schemas"]["Categoria"] | null;
                prioridad?: components["schemas"]["Prioridad"] | null;
                area_sugerida?: components["schemas"]["Area"] | null;
                status?: ("pending" | "classified" | "failed") | null;
                needs_review?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_solicitudes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_request_solicitudes__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    correct_solicitudes__request_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const pathsSolicitudesGetParametersQueryStatusAnyOf0Values: ReadonlyArray<FlattenedDeepRequired<paths>["/solicitudes"]["get"]["parameters"]["query"]["status"]> = ["pending", "classified", "failed"];
export const areaValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Area"]> = ["backend", "frontend", "data", "devops", "producto", "digital_transformation"];
export const categoriaValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Categoria"]> = ["bug", "datos", "acceso", "automatizacion", "consulta", "otro"];
export const idiomaValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Idioma"]> = ["es", "pt"];
export const itemStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Item"]["status"]> = ["pending", "classified", "failed"];
export const itemDetailStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ItemDetail"]["status"]> = ["pending", "classified", "failed"];
export const prioridadValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Prioridad"]> = ["alta", "media", "baja"];
